# Generated by Django 4.2 on 2023-04-21 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='posts_posted',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='posts_posted'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reactions',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='reactions'),
        ),
    ]
