# Generated by Django 4.2 on 2023-05-10 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='exp',
            field=models.PositiveIntegerField(default=0, verbose_name='User Exp'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.PositiveIntegerField(default=1, verbose_name='User level'),
        ),
    ]
