# Generated by Django 4.1.6 on 2023-05-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_comment_date_created_comment_dislikers_and_more'),
        ('users', '0006_customuser_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='main.postsmodel'),
        ),
    ]
