# Generated by Django 4.1.6 on 2023-05-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_customuser_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='points',
            field=models.PositiveBigIntegerField(default=0, verbose_name='points'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='posts_posted',
            field=models.PositiveBigIntegerField(default=0, verbose_name='posts_posted'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='reactions',
            field=models.PositiveBigIntegerField(default=0, verbose_name='reactions'),
        ),
    ]
