# Generated by Django 4.1.6 on 2023-05-22 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_subscribers_set_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True, default='No BIO', verbose_name='User Description'),
        ),
    ]
