# Generated by Django 4.1.6 on 2023-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_customuser_last_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='avatar_visibility',
            field=models.CharField(choices=[('all', 'all'), ('friends', 'friends')], default='all', max_length=7),
        ),
    ]
