# Generated by Django 4.1.6 on 2023-05-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_rename_films_film_alter_film_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='href',
            field=models.URLField(default='a', max_length=255, verbose_name='Href'),
            preserve_default=False,
        ),
    ]
