# Generated by Django 4.1.6 on 2023-05-27 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Films',
            new_name='Film',
        ),
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name': 'Sponsor Film', 'verbose_name_plural': 'Sponsor Films'},
        ),
    ]
