# Generated by Django 4.2 on 2023-04-14 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, verbose_name='User Name')),
                ('is_staff', models.CharField(max_length=10, verbose_name='Is Staff')),
                ('post_title', models.CharField(max_length=255, verbose_name='Post Title')),
                ('post_text', models.TextField(verbose_name='Post Text')),
            ],
        ),
    ]
