# Generated by Django 4.2 on 2023-04-21 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_remove_postsmodel_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='content',
            field=models.TextField(verbose_name='Post Content'),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='img',
            field=models.ImageField(upload_to='', verbose_name='Post Image'),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Post Title'),
        ),
    ]
