# Generated by Django 4.2 on 2023-04-21 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_postsmodel_sender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodel',
            name='sender',
        ),
    ]
