# Generated by Django 4.1.6 on 2023-04-22 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_like'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
