# Generated by Django 4.2 on 2023-04-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_postsmodel_dislike_remove_postsmodel_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='dislike_count',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Dislikes Count'),
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='like_count',
            field=models.PositiveBigIntegerField(blank=True, default=0, verbose_name='Likes Count'),
        ),
    ]
