# Generated by Django 4.2 on 2023-05-10 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_postsmodel_datatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='datatime',
            field=models.DateTimeField(auto_created=True, verbose_name='Data Time'),
        ),
    ]
