# Generated by Django 4.2 on 2023-05-10 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_alter_postsmodel_datatime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='datatime',
            field=models.DateField(auto_created=True, blank=True, verbose_name='Data'),
        ),
    ]
