# Generated by Django 4.2 on 2023-05-10 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_alter_postsmodel_datatime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodel',
            name='datatime',
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Data Created'),
        ),
    ]
