# Generated by Django 4.1.6 on 2023-05-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_postsmodel_comments_count_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodel',
            name='comments',
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='comments',
            field=models.ManyToManyField(to='main.comment'),
        ),
    ]
