# Generated by Django 4.1.6 on 2023-05-21 18:37

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0035_remove_postsmodel_comments_postsmodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Data Created'),
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikers',
            field=models.ManyToManyField(blank=True, related_name='com_dislikers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='likers',
            field=models.ManyToManyField(blank=True, related_name='com_likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
