# Generated by Django 4.1.6 on 2023-05-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_comment_date_created_comment_dislikers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodel',
            name='comments_count',
        ),
        migrations.AlterField(
            model_name='postsmodel',
            name='comments',
            field=models.ManyToManyField(blank=True, to='main.comment'),
        ),
    ]
