# Generated by Django 4.1.6 on 2023-05-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_remove_postsmodel_comments_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='post_title',
            field=models.CharField(max_length=100, verbose_name='Post Title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=15, verbose_name='Tag Name'),
        ),
    ]
