# Generated by Django 4.1.6 on 2023-05-25 14:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about_us', '0002_aboutustext_alter_contactus_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastestUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=255, verbose_name='Update Title')),
                ('text', models.TextField(verbose_name='Update Text')),
            ],
            options={
                'verbose_name': 'Lastest Update',
                'verbose_name_plural': 'Lastest Updates',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutustext',
            options={'verbose_name': 'About Us Text', 'verbose_name_plural': 'About Us Text'},
        ),
    ]
