# Generated by Django 4.1.6 on 2023-06-02 17:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='date_created',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now, verbose_name='Data Created'),
        ),
    ]
