# Generated by Django 4.1.6 on 2023-06-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_chatmessage_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='unread_messages',
            field=models.PositiveIntegerField(default=0, verbose_name='Unread Messages'),
        ),
    ]
