# Generated by Django 4.1.6 on 2023-06-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage_reply_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='reply_to',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.DO_NOTHING, related_name='repl', to='chat.chatmessage'),
        ),
    ]
