# Generated by Django 4.1.6 on 2023-04-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_postsmodel_dislikers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postsmodel',
            name='post_image',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Post Image'),
        ),
    ]
