# Generated by Django 4.1.6 on 2023-04-22 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_postsmodel_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postsmodel',
            name='post_tags',
            field=models.CharField(blank=True, max_length=100, verbose_name='Post Title'),
        ),
    ]
