# Generated by Django 4.2 on 2023-04-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_postsmodel_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodel',
            name='dislike',
        ),
        migrations.RemoveField(
            model_name='postsmodel',
            name='like',
        ),
    ]
