# Generated by Django 4.2 on 2023-04-23 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_postsmodel_dislike_count_postsmodel_like_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postsmodel',
            name='dislike_count',
        ),
        migrations.RemoveField(
            model_name='postsmodel',
            name='like_count',
        ),
    ]
