# Generated by Django 4.2 on 2023-04-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_remove_postsmodel_dislike_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Tag Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='postsmodel',
            name='post_tags',
        ),
        migrations.AddField(
            model_name='postsmodel',
            name='post_tags',
            field=models.ManyToManyField(to='main.tags'),
        ),
    ]
