# Generated by Django 4.2 on 2023-05-09 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_rename_tags_tag'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostsModel',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
