# Generated by Django 4.2 on 2023-05-10 19:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_exp_customuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='date_joined',
            field=models.DateTimeField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
