# Generated by Django 4.1.6 on 2023-05-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_customuser_avatar_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hide_dislikes',
            field=models.BooleanField(default=True, verbose_name='Hide Dislikes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hide_favorites',
            field=models.BooleanField(default=True, verbose_name='Hide Favorites'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='hide_likes',
            field=models.BooleanField(default=True, verbose_name='Hide Likes'),
        ),
    ]
