# Generated by Django 4.1.6 on 2023-05-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_customuser_hide_dislikes_customuser_hide_favorites_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hide_dislikes',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hide_favorites',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='hide_likes',
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_dislikes',
            field=models.BooleanField(default=False, verbose_name='Hide Dislikes'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_favorites',
            field=models.BooleanField(default=False, verbose_name='Hide Favorites'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='show_likes',
            field=models.BooleanField(default=False, verbose_name='Hide Likes'),
        ),
    ]
